[database]

DB_HOST = 'ec2-79-125-127-60.eu-west-1.compute.amazonaws.com'
DB_PORT = 5432

DB_NAME = 'app_google_links'
DB_USER = 'admin'
DB_PASS = 'qwerty'

[redis]

REDIS_HOST = 'localhost'
REDIS_PORT = 6379